# Generated by Django 4.1.1 on 2022-09-25 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name', max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number', max_length=20)),
                ('address', models.CharField(help_text='Address', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('owner', models.ForeignKey(help_text='Created by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
